### PR TITLE
ErrorBudget class work 

### PR DESCRIPTION
**Pull request by steigersg**
Consolidates the ErrorBudget and ErrorBudgetMCMC classes into one class with a `run' method and `run_mcmc' method to differentiate the two modes. Also adds an ExosimsWrapper class to handle the actual running and output formatting for EXOSIMS to declutter the ErrorBudget class. The ErrorBudget class is now only responsible for calculating the WFS&C variables and performing all file generation and handling.

These changes cut the total length of code almost in half. It is less than that now since more expansive docstrings have been added. 

Additional help wanted:
- General thoughts/notes
- Adding some MCMC tutorial documentation (to the README?)
- testing the changes on this branch with the MCMC functionality

### CODE REVIEW

**Comment by chen-pin** [comment]
Running the sample command <run_ebs scienceInstruments -sub QE -c inputs/parameters.yml> returns the error shown in the attached image.  
image

**Comment by steigersg** [comment]
> Running the sample command <run_ebs scienceInstruments -sub QE -c inputs/parameters.yml> returns the error shown in the attached image.
> image

Fixed in most recent commits - thanks for catching that!

**Comment by chen-pin** [comment]
@steigersg :   please review the latest commit.

**Comment by steigersg** [comment]
@chen-pin This is ready for your final review. Since the last changes I only removed some unused imports and commented out code. I added issues for additional things that I came across which will need addressing but I think can be moved to a separate modular PR. A note is that the test_mcmc_log_probability test does fail on my current branch with these updates, but I am not confident on the desired behavior here.

**Pull request merged**
